dist: trusty
jdk: oraclejdk8
language: java
services:
  - postgresql
  - docker
env:
  global:
    - secure: "Cyb9BjLKPqhGFHi+/hf0ujywevWFUKQou4EnGaUraLx1YDBag34xnxnKbdoAKW/MyQYQJTodkGTjeHBFaWwtNX80+NASZaPIXE7kNND4J3fEHqGia3R61RO3EQK/KLBLf/u/2fDOAjB0kBN5anvyVljQJhlKVT3O8fx/tfZ1BHy8ugPrToMf1HlMy8U8DyRl6QlkODdN95oTY+pAqNWnX6dHP8go+k3xANFoygDPcjoJzdIKwXlqNq3Mi1+IBJ8Gr5ZcWRun9JNwfNMBiUtD6/Bz+Ivr4NjVXUEUbMj3uVRBlYKW0ESr5gwpns4j4UmIX/j5ebTlC20cfoIThQ8lklvJG0kK3oJba1PhmoNi9Xv8cxBkxVtln/3I2KZbhWpFUMbJCy55ew7+k3K9bSowZ/IZzy7V2GH0+SbxRUTJbW42Mra5dNlOe8pjz4toT4K36AqhPNhhxJUlug1Tm5d4uJ6jL9JzK6irzR3/e+LukCu+j/v6GFzcfTncCoLsTtrgH37miEVMQmDhyWGnP6RxTXmsigbRgKl2TBjwDzgvGt92rWDD5GmnBiX7WRCz6Yj1cl/3ibQluDgQWi1QYHcI9yPJU4ymKV42IrksuWPQhnlU9N5TI6cKHjV67q3Z1ydUFq0v16UddiYQizCecpZ7DTvhkFjFcojzHu9HtvW5pOc="
    - secure: "WNI1uYnryJP3+6FLl4J/Ft1TyjzPWP6iF9qvWYoaNdQRI45tlx5q7NHeshihsFySElqPqpr7IENRJYaJpRNLBM+s6yS5+Z3sbta4OtXiFMRJ2XqAP/sl33VZia0h4HgZoOLshAUyEMUvA4SlWyMjCNjkH714K+X/QCnBGXcEG3m1y0eUNyYAmWgDEYji+fs26egjUaDqI6VN5c9/Jhy3VrnjzTXu2OiI281ySAQmi1OSvQytMSuKqve8fo4XlZ2eXTueRgAsYMpvm+gMZiKhwPiGECTOj0rKT3nuK3SybLltJv6yuWJvD+egqhhafBfapJVMVOdCipcupkqGAADKXjnxYic+Cj+7QbG5IEIvPnMJCtziWC1gmy6lIscFEp96OOMhyDDGO14YEbUWhf+lkWKS9YfwVZ1Q9Syo/6/aktPpfxW/HowSl4TpKwpjPE/AdDqM/Vj0Dd8RCqbTTzBRPLWgbdEz5VrTYqcFmcrZIlGaOUce9xmGjNwugyyRJa04FH+/OzdNeHiWS1xbvwe5jAQ62Q2hX9obU0uwfoMfPr8ApfmFH1hXj4jHptNtawHGGXGVmkqG4b8sOpFGs5s9QQ4SHGKYNqOVUsGlNd8pkfv0xPB/aXFg9HqYTMh73a7koqnx08l9iorFaPgflISV0JLMRiSK1Z4v6/ATYplJCdc="
    - secure: "T3J1vPLeA+C29V+aPwYJr9GRA5gX7mxdS62nzNgNy1th8onJ6agQ+AFxOWRBFOL3yZ9WCq/NAZ4rID8ZvAIx5oI+d+Ghcm4f3Y2r/+MNnh/nTNq3CFeTyxGwuDEl38J1Ly9bPbvmFae8wejgmxjcPi1Ggwuf1IjN+Sf3FoYut4cUnvNcsf0Dxb+7zRoHLv3odNtK0v6g9DtG7idcmyFFAN1EryZHyI6qW1jVhYymqWPjh9xGRSsgcQw60UzU0uUP2oPTlgJlHklxN7zYbVU3L3V0QyJun4F/qIiRAKcgH26t5oPTeU7TJTQiooJR8lDXPfczvZISuhaPBVKwQ000YyHdZRxTeYFZv416+OXf+gr7twWLhPW/OQeLNHIOXVFMcx9DqvSYTlPsFXvlltycU84cu3U2gx0MJa3bWa3xylmp889DKeKuSZI//2p+Fm/YHtEFIxPfyyH/wPkM1P4Tr11U5XNGN+1SkWXesv2xF56mU+lPkCafzF5409rusc4UepGwoO6ug47GalKd4tlERMoPvLvEqGDdRNhWpzefFnZD+XKHVGAxM6nh05eZTXrfhYLUbcZdYyvgkumMshC5hH/lOxrKuRzCjaP/9NZ5sDDIFlm9ddVFQNUbb5NTZuswp27SJ3mQjVXKoxclx2c+D3M+37pcpZ4dBjedhTIgJqI="
    - COMMIT=${TRAVIS_COMMIT::7}

script:
  - ./mvnw clean install -B

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
  - export IMAGE_NAME=myapi/main-repo
  - docker build -t $IMAGE_NAME:latest .
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: simpleproject-mt